# Generated by Django 4.2.7 on 2023-11-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subway',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='subway',
            old_name='lineNumber',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='subway',
            old_name='longtitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='subway',
            old_name='stationName',
            new_name='name',
        ),
    ]
