# Generated by Django 4.2.7 on 2023-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0004_alter_subway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subway',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
