# Generated by Django 4.2.7 on 2023-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('gidChar', models.CharField(max_length=100)),
                ('gidCode1', models.IntegerField()),
                ('gidCode2', models.IntegerField()),
                ('depth10Risk', models.FloatField()),
                ('depth20Risk', models.FloatField()),
                ('depth50Risk', models.FloatField()),
            ],
            options={
                'db_table': 'floodRisk',
            },
        ),
    ]
