# Generated by Django 4.2.7 on 2023-11-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('floodRisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodrisk',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
    ]
