# Generated by Django 4.2.7 on 2023-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxLat', models.FloatField(default=0)),
                ('maxLng', models.FloatField(default=0)),
                ('minLat', models.FloatField(default=0)),
                ('minLng', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
