# Generated by Django 4.2.7 on 2023-11-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxLat', models.FloatField(default=0)),
                ('maxLng', models.FloatField(default=0)),
                ('minLat', models.FloatField(default=0)),
                ('minLng', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
            options={
                'db_table': 'subRegion',
            },
        ),
    ]
