# Generated by Django 4.2.7 on 2023-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_subregion_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregion',
            name='maxLat',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='maxLng',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='minLat',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='minLng',
        ),
        migrations.AddField(
            model_name='subregion',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
